services:
  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    volumes:
      # ①  bind‑mount *only* your source tree (which contains no node_modules
      #    because of .dockerignore) for hot‑reload:
      - ../app:/app
      # ②  overlay an empty named volume on /app/node_modules so the host copy
      #    can never leak in:
      - node_modules:/app/node_modules
    command: >
      sh -c "CHOKIDAR_USEPOLLING=true
         npm ci --include=optional --no-audit --loglevel=error &&
         exec npx vite --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    networks:
      - traefik_network

volumes:
  node_modules:

networks:
  traefik_network:
    external: true
