services:
  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    volumes:
      - ../app:/app
      - node_modules:/app/node_modules
    working_dir: /app
    expose:
      - "5173"
    networks:
      - traefik_network
networks:
  traefik_network:
    external: true
volumes:
  node_modules:
